name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Making ZIP
        run: 7z a -m0=Copy -tzip voxels_ps_${{ github.run_number }}.zip exhumed.def psgdx.def voxels.def license.txt readme.txt KVX
          
      - name: Deleting older releases
        uses: bubkoo/delete-stale-releases@v1.0.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          keep_latest_count: 0
          delete_tags: true
          exclude: v*
          include: p*
          include_draft: false
          include_prerelease: true
          
      - name: Creating new release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: voxels_ps_${{ github.run_number }}.zip
          release: p${{ github.run_number }}
          prerelease: true
          draft: false
